-- MySQL Script generated by MySQL Workbench
-- 11/22/14 02:26:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PAYDAY
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PAYDAY
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PAYDAY` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `PAYDAY` ;

-- -----------------------------------------------------
-- Table `PAYDAY`.`BusinessTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAYDAY`.`BusinessTable` (
  `business_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` INT NULL,
  `phone` INT NULL,
  PRIMARY KEY (`businessId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAYDAY`.`TransactionsTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAYDAY`.`TransactionsTable` (
  `business_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  `date_created` timestamp default now(),
  `type` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  `BusinessTable_businessId` INT NOT NULL,
  PRIMARY KEY (`businessId`, `transactionId`, `BusinessTable_businessId`),
  INDEX `fk_TransactionsTable_BusinessTable_idx` (`BusinessTable_businessId` ASC),
  CONSTRAINT `fk_TransactionsTable_BusinessTable`
    FOREIGN KEY (`BusinessTable_businessId`)
    REFERENCES `PAYDAY`.`BusinessTable` (`businessId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAYDAY`.`UsersTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAYDAY`.`UsersTable` (
  `businessId` INT NOT NULL,
  `userId` INT NOT NULL,
  `userEmail` VARCHAR(45) NOT NULL,
  `userFirstName` VARCHAR(45) NULL,
  `userLastName` VARCHAR(45) NULL,
  `userPassword` VARCHAR(45) NULL,
  `userImage` VARCHAR(45) NULL,
  `userBio` VARCHAR(45) NULL,
  `userBankRouting` INT NULL,
  `userBankAccount` INT NULL,
  `isManager` VARCHAR(45) NULL,
  `phoneNumber` INT NULL,
  `BusinessTable_businessId` INT NOT NULL,
  PRIMARY KEY (`businessId`, `userId`, `userEmail`, `BusinessTable_businessId`),
  INDEX `fk_UsersTable_BusinessTable1_idx` (`BusinessTable_businessId` ASC),
  CONSTRAINT `fk_UsersTable_BusinessTable1`
    FOREIGN KEY (`BusinessTable_businessId`)
    REFERENCES `PAYDAY`.`BusinessTable` (`businessId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAYDAY`.`WorktimeTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAYDAY`.`WorktimeTable` (
  `userId` INT NOT NULL,
  `worktimeId` INT NOT NULL,
  `timeStampIn` VARCHAR(45) NULL,
  `timeStampOut` VARCHAR(45) NULL,
  `UsersTable_businessId` INT NOT NULL,
  `UsersTable_userId` INT NOT NULL,
  `UsersTable_userEmail` VARCHAR(45) NOT NULL,
  `UsersTable_BusinessTable_businessId` INT NOT NULL,
  PRIMARY KEY (`userId`, `worktimeId`),
  INDEX `fk_WorktimeTable_UsersTable1_idx` (`UsersTable_businessId` ASC, `UsersTable_userId` ASC, `UsersTable_userEmail` ASC, `UsersTable_BusinessTable_businessId` ASC),
  CONSTRAINT `fk_WorktimeTable_UsersTable1`
    FOREIGN KEY (`UsersTable_businessId` , `UsersTable_userId` , `UsersTable_userEmail` , `UsersTable_BusinessTable_businessId`)
    REFERENCES `PAYDAY`.`UsersTable` (`businessId` , `userId` , `userEmail` , `BusinessTable_businessId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAYDAY`.`CategoriesTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAYDAY`.`CategoriesTable` (
  `businessId` INT NOT NULL,
  `categoryId` INT NULL,
  `categoryName` VARCHAR(45) NULL,
  `BusinessTable_businessId` INT NOT NULL,
  PRIMARY KEY (`businessId`),
  INDEX `fk_CategoriesTable_BusinessTable1_idx` (`BusinessTable_businessId` ASC),
  CONSTRAINT `fk_CategoriesTable_BusinessTable1`
    FOREIGN KEY (`BusinessTable_businessId`)
    REFERENCES `PAYDAY`.`BusinessTable` (`businessId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
